version: "3"
services:
  nas-tools:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: nas-tools:test
    container_name: nas-tools-test
    restart: always
    # hostname: nas-tools
    network_mode: bridge
    ports:
      - 33001:3000 # 默认的webui控制端口
    volumes:
      - ./config-test-docker:/config # 冒号左边请修改为你想保存配置的路径
      # - /你的媒体目录:/你想设置的容器内能见到的目录 # 媒体目录，多个目录需要分别映射进来，需要满足配置文件说明中的要求
    environment:
      - PUID=0 # 想切换为哪个用户来运行程序，该用户的uid
      - PGID=0 # 想切换为哪个用户来运行程序，该用户的gid
      - UMASK=000 # 掩码权限，默认000，可以考虑设置为022
      #- REPO_URL=https://ghproxy.com/https://github.com/boeto/nas-tools.git  # 当你访问github网络很差时，可以考虑解释本行注释
