name: NAStool Docker Dev
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - version.py
      - .github/workflows/build-dev.yml
      - package_list.txt
      - requirements.txt
      - Dockerfile.dev

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: "true"

      - name: Release version
        id: release_version
        run: |
          app_version=$(cat version.py |sed -ne "s/APP_VERSION\s=\s'v\(.*\)'/\1/gp")
          echo "app_version:::$app_version"
          echo "app_version=$app_version" >> $GITHUB_ENV
          echo "APP_VERSION=$app_version" >> $GITHUB_ENV

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check Vars
        run: |
          echo "env.app_version:::${{ env.app_version }}"
          echo "env.APP_VERSION:::${{ env.APP_VERSION }}"
          echo "#######################"
          echo "pwd:::"
          pwd
          echo "#######################"
          echo "ls::"
          ls
          echo "#######################"
          echo "ls docker::"
          ls docker
          echo "#######################"
          echo "ls workspace docker:::"
          ls "${{ github.workspace }}/docker"
          echo "#######################"

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: docker
          file: Dockerfile.dev
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:latest-beta
